#!/bin/bash
# Helper script to generate Noir proof + Starknet calldata

set -euo pipefail

CIRCUIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/donation_badge"
cd "$CIRCUIT_DIR"

if [[ $# -lt 3 ]]; then
    echo "Usage: $0 <donation_amount_cents> <donor_secret> <badge_tier>"
    echo "  badge_tier: 1=Bronze, 2=Silver, 3=Gold"
    exit 1
fi

AMOUNT="$1"
SECRET="$2"
TIER="$3"

case "$TIER" in
    1) THRESHOLD=1000 ;;
    2) THRESHOLD=10000 ;;
    3) THRESHOLD=100000 ;;
    *) echo "Invalid badge tier: $TIER" && exit 1 ;;
esac

echo "=== Donation Badge Proof Generator ==="
echo "Amount (cents): $AMOUNT"
echo "Threshold:      $THRESHOLD"
echo "Badge tier:     $TIER"
echo ""

echo "=== Computing Poseidon commitment ==="
RESULT=$(
  SECRET_VALUE="$SECRET" AMOUNT_VALUE="$AMOUNT" node --input-type=module - <<'EOF'
import { buildPoseidon } from 'circomlibjs';
const poseidon = await buildPoseidon();
const secretDigits = process.env.SECRET_VALUE.split('').map(c => c.charCodeAt(0)).join('');
const secretField = BigInt(secretDigits || '0');
const amount = BigInt(process.env.AMOUNT_VALUE);
const hash = poseidon([secretField, amount]);
console.log(secretField.toString());
console.log(poseidon.F.toString(hash));
EOF
)
SECRET_FIELD=$(echo "$RESULT" | sed -n '1p')
COMMITMENT=$(echo "$RESULT" | sed -n '2p')
echo "Commitment: $COMMITMENT"
echo ""

cat > Prover.toml <<EOF
# Auto-generated by generate-proof.sh
donation_amount = "$AMOUNT"
donor_secret = "$SECRET_FIELD"
threshold = "$THRESHOLD"
badge_tier = "$TIER"
donation_commitment = "$COMMITMENT"
EOF

echo "Prover.toml updated"
echo ""

echo "=== Compiling Noir circuit ==="
nargo compile
echo ""

echo "=== Generating witness ==="
nargo execute witness
echo ""

echo "=== Generating proof (barretenberg) ==="
bb prove -s ultra_honk --oracle_hash keccak \
    -b ./target/donation_badge.json \
    -w ./target/witness.gz \
    -o ./target/proof
mv ./target/proof ./target/proof.bin
echo ""

echo "=== Verifying proof locally ==="
bb verify -s ultra_honk --oracle_hash keccak \
    -k ./target/vk.bin \
    -p ./target/proof.bin || true
echo ""

echo "=== Generating Starknet calldata via Garaga ==="
CALLOUT="$(dirname "$CIRCUIT_DIR")/calldata.json"
garaga calldata \
    --system ultra_keccak_honk \
    --vk ./target/vk.bin \
    --proof ./target/proof.bin \
    --format starkli > "$CALLOUT"
echo ""

echo "Proof:     $CIRCUIT_DIR/target/proof.bin"
echo "Calldata:  $CALLOUT"
echo ""
echo "Public inputs:"
echo "  threshold           = $THRESHOLD"
echo "  donation_commitment = $COMMITMENT"
echo "  badge_tier          = $TIER"

